export const Country = [
  { country: 'Afganistan', code: '93', iso: 'AF' },
  { country: 'Albania', code: '355', iso: 'AL' },
  { country: 'Algieria', code: '213', iso: 'DZ' },
  { country: 'Samoa Amerykańskie', code: '1-684', iso: 'AS' },
  { country: 'Andora', code: '376', iso: 'AD' },
  { country: 'Angola', code: '244', iso: 'AO' },
  { country: 'Anguilla', code: '1-264', iso: 'AI' },
  { country: 'Antarktyda', code: '672', iso: 'AQ' },
  { country: 'Antigua i Barbuda', code: '1-268', iso: 'AG' },
  { country: 'Argentyna', code: '54', iso: 'AR' },
  { country: 'Armenia', code: '374', iso: 'AM' },
  { country: 'Aruba', code: '297', iso: 'AW' },
  { country: 'Australia', code: '61', iso: 'AU' },
  { country: 'Austria', code: '43', iso: 'AT' },
  { country: 'Azerbejdżan', code: '994', iso: 'AZ' },
  { country: 'Bahamy', code: '1-242', iso: 'BS' },
  { country: 'Bahrajn', code: '973', iso: 'BH' },
  { country: 'Bangladesz', code: '880', iso: 'BD' },
  { country: 'Barbados', code: '1-246', iso: 'BB' },
  { country: 'Białoruś', code: '375', iso: 'BY' },
  { country: 'Belgia', code: '32', iso: 'BE' },
  { country: 'Belize', code: '501', iso: 'BZ' },
  { country: 'Benin', code: '229', iso: 'BJ' },
  { country: 'Bermudy', code: '1-441', iso: 'BM' },
  { country: 'Bhutan', code: '975', iso: 'BT' },
  { country: 'Boliwia', code: '591', iso: 'BO' },
  { country: 'Bośnia i Hercegowina', code: '387', iso: 'BA' },
  { country: 'Botswana', code: '267', iso: 'BW' },
  { country: 'Brazylia', code: '55', iso: 'BR' },
  { country: 'Brytyjskie Terytorium Oceanu Indyjskiego', code: '246', iso: 'IO' },
  { country: 'Brytyjskie Wyspy Dziewicze', code: '1-284', iso: 'VG' },
  { country: 'Brunei', code: '673', iso: 'BN' },
  { country: 'Bułgaria', code: '359', iso: 'BG' },
  { country: 'Burkina Faso', code: '226', iso: 'BF' },
  { country: 'Burundi', code: '257', iso: 'BI' },
  { country: 'Kambodża', code: '855', iso: 'KH' },
  { country: 'Kamerun', code: '237', iso: 'CM' },
  { country: 'Kanada', code: '1', iso: 'CA' },
  { country: 'Republika Zielonego Przylądka', code: '238', iso: 'CV' },
  { country: 'Kajmany', code: '1-345', iso: 'KY' },
  { country: 'Republika Środkowoafrykańska', code: '236', iso: 'CF' },
  { country: 'Czad', code: '235', iso: 'TD' },
  { country: 'Chile', code: '56', iso: 'CL' },
  { country: 'Chiny', code: '86', iso: 'CN' },
  { country: 'Wyspa Bożego Narodzenia', code: '61', iso: 'CX' },
  { country: 'Wyspy Kokosowe', code: '61', iso: 'CC' },
  { country: 'Kolumbia', code: '57', iso: 'CO' },
  { country: 'Komory', code: '269', iso: 'KM' },
  { country: 'Wyspy Cooka', code: '682', iso: 'CK' },
  { country: 'Kostaryka', code: '506', iso: 'CR' },
  { country: 'Chorwacja', code: '385', iso: 'HR' },
  { country: 'Kuba', code: '53', iso: 'CU' },
  { country: 'Curaçao', code: '599', iso: 'CW' },
  { country: 'Cypr', code: '357', iso: 'CY' },
  { country: 'Czechy', code: '420', iso: 'CZ' },
  { country: 'Demokratyczna Republika Konga', code: '243', iso: 'CD' },
  { country: 'Dania', code: '45', iso: 'DK' },
  { country: 'Dżibuti', code: '253', iso: 'DJ' },
  { country: 'Dominika', code: '1-767', iso: 'DM' },
  { country: 'Dominikana', code: '1-809, 1-829, 1-849', iso: 'DO' },
  { country: 'Timor Wschodni', code: '670', iso: 'TL' },
  { country: 'Ekwador', code: '593', iso: 'EC' },
  { country: 'Egipt', code: '20', iso: 'EG' },
  { country: 'Salwador', code: '503', iso: 'SV' },
  { country: 'Gwinea Równikowa', code: '240', iso: 'GQ' },
  { country: 'Erytrea', code: '291', iso: 'ER' },
  { country: 'Estonia', code: '372', iso: 'EE' },
  { country: 'Etiopia', code: '251', iso: 'ET' },
  { country: 'Falklandy', code: '500', iso: 'FK' },
  { country: 'Wyspy Owcze', code: '298', iso: 'FO' },
  { country: 'Fidżi', code: '679', iso: 'FJ' },
  { country: 'Finlandia', code: '358', iso: 'FI' },
  { country: 'Francja', code: '33', iso: 'FR' },
  { country: 'Polinezja Francuska', code: '689', iso: 'PF' },
  { country: 'Gabon', code: '241', iso: 'GA' },
  { country: 'Gambia', code: '220', iso: 'GM' },
  { country: 'Gruzja', code: '995', iso: 'GE' },
  { country: 'Niemcy', code: '49', iso: 'DE' },
  { country: 'Ghana', code: '233', iso: 'GH' },
  { country: 'Gibraltar', code: '350', iso: 'GI' },
  { country: 'Grecja', code: '30', iso: 'GR' },
  { country: 'Grenlandia', code: '299', iso: 'GL' },
  { country: 'Grenada', code: '1-473', iso: 'GD' },
  { country: 'Guam', code: '1-671', iso: 'GU' },
  { country: 'Gwatemala', code: '502', iso: 'GT' },
  { country: 'Guernsey', code: '44-1481', iso: 'GG' },
  { country: 'Gwinea', code: '224', iso: 'GN' },
  { country: 'Gwinea Bissau', code: '245', iso: 'GW' },
  { country: 'Gujana', code: '592', iso: 'GY' },
  { country: 'Haiti', code: '509', iso: 'HT' },
  { country: 'Honduras', code: '504', iso: 'HN' },
  { country: 'Hongkong', code: '852', iso: 'HK' },
  { country: 'Węgry', code: '36', iso: 'HU' },
  { country: 'Islandia', code: '354', iso: 'IS' },
  { country: 'Indie', code: '91', iso: 'IN' },
  { country: 'Indonezja', code: '62', iso: 'ID' },
  { country: 'Iran', code: '98', iso: 'IR' },
  { country: 'Irak', code: '964', iso: 'IQ' },
  { country: 'Irlandia', code: '353', iso: 'IE' },
  { country: 'Wyspa Man', code: '44-1624', iso: 'IM' },
  { country: 'Izrael', code: '972', iso: 'IL' },
  { country: 'Włochy', code: '39', iso: 'IT' },
  { country: 'Wybrzeże Kości Słoniowej', code: '225', iso: 'CI' },
  { country: 'Jamajka', code: '1-876', iso: 'JM' },
  { country: 'Japonia', code: '81', iso: 'JP' },
  { country: 'Jersey', code: '44-1534', iso: 'JE' },
  { country: 'Jordania', code: '962', iso: 'JO' },
  { country: 'Kazachstan', code: '7', iso: 'KZ' },
  { country: 'Kenia', code: '254', iso: 'KE' },
  { country: 'Kiribati', code: '686', iso: 'KI' },
  { country: 'Kosowo', code: '383', iso: 'XK' },
  { country: 'Kuwejt', code: '965', iso: 'KW' },
  { country: 'Kirgistan', code: '996', iso: 'KG' },
  { country: 'Laos', code: '856', iso: 'LA' },
  { country: 'Łotwa', code: '371', iso: 'LV' },
  { country: 'Liban', code: '961', iso: 'LB' },
  { country: 'Lesotho', code: '266', iso: 'LS' },
  { country: 'Liberia', code: '231', iso: 'LR' },
  { country: 'Libia', code: '218', iso: 'LY' },
  { country: 'Liechtenstein', code: '423', iso: 'LI' },
  { country: 'Litwa', code: '370', iso: 'LT' },
  { country: 'Luksemburg', code: '352', iso: 'LU' },
  { country: 'Makau', code: '853', iso: 'MO' },
  { country: 'Macedonia Północna', code: '389', iso: 'MK' },
  { country: 'Madagaskar', code: '261', iso: 'MG' },
  { country: 'Malawi', code: '265', iso: 'MW' },
  { country: 'Malezja', code: '60', iso: 'MY' },
  { country: 'Malediwy', code: '960', iso: 'MV' },
  { country: 'Mali', code: '223', iso: 'ML' },
  { country: 'Malta', code: '356', iso: 'MT' },
  { country: 'Wyspy Marshalla', code: '692', iso: 'MH' },
  { country: 'Mauretania', code: '222', iso: 'MR' },
  { country: 'Mauritius', code: '230', iso: 'MU' },
  { country: 'Majotta', code: '262', iso: 'YT' },
  { country: 'Meksyk', code: '52', iso: 'MX' },
  { country: 'Mikronezja', code: '691', iso: 'FM' },
  { country: 'Mołdawia', code: '373', iso: 'MD' },
  { country: 'Monako', code: '377', iso: 'MC' },
  { country: 'Mongolia', code: '976', iso: 'MN' },
  { country: 'Czarnogóra', code: '382', iso: 'ME' },
  { country: 'Montserrat', code: '1-664', iso: 'MS' },
  { country: 'Maroko', code: '212', iso: 'MA' },
  { country: 'Mozambik', code: '258', iso: 'MZ' },
  { country: 'Myanmar', code: '95', iso: 'MM' },
  { country: 'Namibia', code: '264', iso: 'NA' },
  { country: 'Nauru', code: '674', iso: 'NR' },
  { country: 'Nepal', code: '977', iso: 'NP' },
  { country: 'Holandia', code: '31', iso: 'NL' },
  { country: 'Antyle Holenderskie', code: '599', iso: 'AN' },
  { country: 'Nowa Kaledonia', code: '687', iso: 'NC' },
  { country: 'Nowa Zelandia', code: '64', iso: 'NZ' },
  { country: 'Nikaragua', code: '505', iso: 'NI' },
  { country: 'Niger', code: '227', iso: 'NE' },
  { country: 'Nigeria', code: '234', iso: 'NG' },
  { country: 'Niue', code: '683', iso: 'NU' },
  { country: 'Korea Północna', code: '850', iso: 'KP' },
  { country: 'Mariany Północne', code: '1-670', iso: 'MP' },
  { country: 'Norwegia', code: '47', iso: 'NO' },
  { country: 'Oman', code: '968', iso: 'OM' },
  { country: 'Pakistan', code: '92', iso: 'PK' },
  { country: 'Palau', code: '680', iso: 'PW' },
  { country: 'Palestyna', code: '970', iso: 'PS' },
  { country: 'Panama', code: '507', iso: 'PA' },
  { country: 'Papua-Nowa Gwinea', code: '675', iso: 'PG' },
  { country: 'Paragwaj', code: '595', iso: 'PY' },
  { country: 'Peru', code: '51', iso: 'PE' },
  { country: 'Filipiny', code: '63', iso: 'PH' },
  { country: 'Pitcairn', code: '64', iso: 'PN' },
  { country: 'Polska', code: '48', iso: 'PL' },
  { country: 'Portugalia', code: '351', iso: 'PT' },
  { country: 'Portoryko', code: '1-787, 1-939', iso: 'PR' },
  { country: 'Katar', code: '974', iso: 'QA' },
  { country: 'Kongo', code: '242', iso: 'CG' },
  { country: 'Reunion', code: '262', iso: 'RE' },
  { country: 'Rumunia', code: '40', iso: 'RO' },
  { country: 'Rosja', code: '7', iso: 'RU' },
  { country: 'Rwanda', code: '250', iso: 'RW' },
  { country: 'Saint Barthelemy', code: '590', iso: 'BL' },
  { country: 'Saint Helena', code: '290', iso: 'SH' },
  { country: 'Saint Kitts i Nevis', code: '1-869', iso: 'KN' },
  { country: 'Saint Lucia', code: '1-758', iso: 'LC' },
  { country: 'Saint Martin', code: '590', iso: 'MF' },
  { country: 'Saint Pierre i Miquelon', code: '508', iso: 'PM' },
  { country: 'Saint Vincent i Grenadyny', code: '1-784', iso: 'VC' },
  { country: 'Samoa', code: '685', iso: 'WS' },
  { country: 'San Marino', code: '378', iso: 'SM' },
  { country: 'Wyspy Świętego Tomasza i Książęca', code: '239', iso: 'ST' },
  { country: 'Arabia Saudyjska', code: '966', iso: 'SA' },
  { country: 'Senegal', code: '221', iso: 'SN' },
  { country: 'Serbia', code: '381', iso: 'RS' },
  { country: 'Seszele', code: '248', iso: 'SC' },
  { country: 'Sierra Leone', code: '232', iso: 'SL' },
  { country: 'Singapur', code: '65', iso: 'SG' },
  { country: 'Sint Maarten', code: '1-721', iso: 'SX' },
  { country: 'Słowacja', code: '421', iso: 'SK' },
  { country: 'Słowenia', code: '386', iso: 'SI' },
  { country: 'Wyspy Salomona', code: '677', iso: 'SB' },
  { country: 'Somalia', code: '252', iso: 'SO' },
  { country: 'Republika Południowej Afryki', code: '27', iso: 'ZA' },
  { country: 'Korea Południowa', code: '82', iso: 'KR' },
  { country: 'Sudan Południowy', code: '211', iso: 'SS' },
  { country: 'Hiszpania', code: '34', iso: 'ES' },
  { country: 'Sri Lanka', code: '94', iso: 'LK' },
  { country: 'Sudan', code: '249', iso: 'SD' },
  { country: 'Surinam', code: '597', iso: 'SR' },
  { country: 'Svalbard i Jan Mayen', code: '47', iso: 'SJ' },
  { country: 'Eswatini', code: '268', iso: 'SZ' },
  { country: 'Szwecja', code: '46', iso: 'SE' },
  { country: 'Szwajcaria', code: '41', iso: 'CH' },
  { country: 'Syria', code: '963', iso: 'SY' },
  { country: 'Tajwan', code: '886', iso: 'TW' },
  { country: 'Tadżykistan', code: '992', iso: 'TJ' },
  { country: 'Tanzania', code: '255', iso: 'TZ' },
  { country: 'Tajlandia', code: '66', iso: 'TH' },
  { country: 'Togo', code: '228', iso: 'TG' },
  { country: 'Tokelau', code: '690', iso: 'TK' },
  { country: 'Tonga', code: '676', iso: 'TO' },
  { country: 'Trynidad i Tobago', code: '1-868', iso: 'TT' },
  { country: 'Tunezja', code: '216', iso: 'TN' },
  { country: 'Turcja', code: '90', iso: 'TR' },
  { country: 'Turkmenistan', code: '993', iso: 'TM' },
  { country: 'Turks i Caicos', code: '1-649', iso: 'TC' },
  { country: 'Tuvalu', code: '688', iso: 'TV' },
  { country: 'Wyspy Dziewicze Stanów Zjednoczonych', code: '1-340', iso: 'VI' },
  { country: 'Uganda', code: '256', iso: 'UG' },
  { country: 'Ukraina', code: '380', iso: 'UA' },
  { country: 'Zjednoczone Emiraty Arabskie', code: '971', iso: 'AE' },
  { country: 'Wielka Brytania', code: '44', iso: 'GB' },
  { country: 'Stany Zjednoczone', code: '1', iso: 'US' },
  { country: 'Urugwaj', code: '598', iso: 'UY' },
  { country: 'Uzbekistan', code: '998', iso: 'UZ' },
  { country: 'Vanuatu', code: '678', iso: 'VU' },
  { country: 'Watykan', code: '379', iso: 'VA' },
  { country: 'Wenezuela', code: '58', iso: 'VE' },
  { country: 'Wietnam', code: '84', iso: 'VN' },
  { country: 'Wallis i Futuna', code: '681', iso: 'WF' },
  { country: 'Sahara Zachodnia', code: '212', iso: 'EH' },
  { country: 'Jemen', code: '967', iso: 'YE' },
  { country: 'Zambia', code: '260', iso: 'ZM' },
  { country: 'Zimbabwe', code: '263', iso: 'ZW' }
];

export default Country;
